defaultBaseImage: registry.hub.docker.com/hassioaddons/base-aarch64:8.0.6
defaultPlatforms:
  - linux/arm64
  - linux/amd64
builds:
  - id: telegram-delete-join-messages
    main: .
    ldflags:
      - "-s"
      - "-w"
      - "-X main.version={{.Env.BUILD_VERSION}}"

